version: '3.8'

services:
  node-app:
    build: .
    depends_on:
      - mongo
    environment:
      - DB_URI=mongodb://mongo:27017/your_database
    ports:
      - "3000:3000"

  mongo:
    image: mongo
    container_name: mongodb-container
    ports:
      - "27017:27017"
